CREATE INDEX IF NOT EXISTS  idx_egbs_bill_id ON public.egbs_bill USING btree (id);
CREATE INDEX IF NOT EXISTS  idx_egbs_bill_isactive ON public.egbs_bill USING btree (isactive);
CREATE INDEX IF NOT EXISTS  idx_egbs_bill_tenantid ON public.egbs_bill USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_eg_bs_bill ON public.egbs_bill USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_bill_v1_id ON public.egbs_bill_v1 USING btree (id);
CREATE INDEX IF NOT EXISTS  idx_egbs_bill_v1_isactive ON public.egbs_bill_v1 USING btree (isactive);
CREATE INDEX IF NOT EXISTS  idx_egbs_bill_v1_tenantid ON public.egbs_bill_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_bill_v1 ON public.egbs_bill_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_eg_bs_billaccountdetails ON public.egbs_billaccountdetail USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_billaccountdetails_v1 ON public.egbs_billaccountdetail_v1 USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_businessservice ON public.egbs_billdetail USING btree (businessservice);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_consumercode ON public.egbs_billdetail USING btree (consumercode);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_tenantid ON public.egbs_billdetail USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_eg_bs_billdetail ON public.egbs_billdetail USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_v1_businessservice ON public.egbs_billdetail_v1 USING btree (businessservice);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_v1_consumercode ON public.egbs_billdetail_v1 USING btree (consumercode);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_v1_tenantid ON public.egbs_billdetail_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_billdetail_v1 ON public.egbs_billdetail_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_biz_srvc_det ON public.egbs_business_service_details USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  unq_businessservice ON public.egbs_business_service_details USING btree (businessservice, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_collectedreceipts ON public.egbs_collectedreceipts USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_businessservice ON public.egbs_demand USING btree (businessservice);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_consumercode ON public.egbs_demand USING btree (consumercode);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_consumertype ON public.egbs_demand USING btree (consumertype);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_id ON public.egbs_demand USING btree (id);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_owner ON public.egbs_demand USING btree (owner);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_taxperiodfrom ON public.egbs_demand USING btree (taxperiodfrom);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_taxperiodto ON public.egbs_demand USING btree (taxperiodto);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_tenantid ON public.egbs_demand USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demand ON public.egbs_demand USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  uk_egbs_demand_consumercode_businessservice ON public.egbs_demand USING btree (consumercode, tenantid, taxperiodfrom, taxperiodto, businessservice);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_businessservice ON public.egbs_demand_v1 USING btree (businessservice);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_consumercode ON public.egbs_demand_v1 USING btree (consumercode);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_consumertype ON public.egbs_demand_v1 USING btree (consumertype);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_id ON public.egbs_demand_v1 USING btree (id);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_payer ON public.egbs_demand_v1 USING btree (payer);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_taxperiodfrom ON public.egbs_demand_v1 USING btree (taxperiodfrom);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_taxperiodto ON public.egbs_demand_v1 USING btree (taxperiodto);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_tenantid ON public.egbs_demand_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demand_v1 ON public.egbs_demand_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  uk_egbs_demand_v1_consumercode_businessservice ON public.egbs_demand_v1 USING btree (consumercode, tenantid, taxperiodfrom, taxperiodto, businessservice);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demand_v1_audit ON public.egbs_demand_v1_audit USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_demanddetail_tenantid ON public.egbs_demanddetail USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demanddetail ON public.egbs_demanddetail USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_demanddetail_v1_demandid ON public.egbs_demanddetail_v1 USING btree (demandid);
CREATE INDEX IF NOT EXISTS  idx_egbs_demanddetail_v1_tenantid ON public.egbs_demanddetail_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demanddetail_v1 ON public.egbs_demanddetail_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demanddetail_v1_audit ON public.egbs_demanddetail_v1_audit USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_glcodemaster ON public.egbs_glcodemaster USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_taxheadmaster ON public.egbs_taxheadmaster USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_taxperiod ON public.egbs_taxperiod USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  unq_service_code ON public.egbs_taxperiod USING btree (service, code, tenantid);